### ISSUE TITLE
"a" and "an" should be accepted as synonyms for "one" in more contexts

### ISSUE THREAD

**Issue by nickovs** [DavidAmison/natural_time#20]
There are some cases where "a" or "an" is accepted as a synonym for "one" and there are others where it is not. The use of "now" tends to make it less likely to work correctly. Some examples where it seems to work include:
```
>>> natural_time.natural_time("a week from today")
datetime.datetime(2020, 7, 1, 0, 0)
>>> natural_time.natural_time("a week from tomorrow")
datetime.datetime(2020, 7, 2, 0, 0)
```
Whereas the following fail:
```
>>> natural_time.natural_time("a week from now") 
datetime.datetime(2020, 6, 24, 9, 14)
>>> natural_time.natural_time("an hour from now")
datetime.datetime(2020, 6, 24, 9, 14)
```
However, in those contexts replacing the "a" or "an" with "one" makes it work:
```
>>> natural_time.natural_time("one week from now")                                                                                                                                                           
datetime.datetime(2020, 7, 1, 9, 14, 23)
>>> natural_time.natural_time("one hour from now")                                                                                                                                                           
datetime.datetime(2020, 6, 24, 10, 14, 30)
```
In most it not all cases "a" or "an" should be accepted as an alternative to "one".

**Comment by DavidAmison** [comment]
From a quick initial investigation I believe the problem is actually a result of the word 'now' not being recognised as it is not currently in the dictionary. Adding handling of the word 'now' should resolve the observed issue.

**Comment by DavidAmison** [comment]
In fixing this I also tried to improve the functionality of words with the rel and rel_t tag.

Specific changes made:
- Addition of 'a' and 'an' to num_parse as equivalent to 1 (fixes the specific issue declared here)
- Addition of 'now' to date_words as ['rel', 'now'] and handling in rel_tag() function implemented
- Change to implementation of rel_tag() for words tagged 'tmrw' and 'yest'
- Change to implementation of rel_t_tag() - now starts from a baseline datetime based on the interpretation of the string so far. Previously sentences such as "a week tomorrow at 5pm" would lose the information interpreted from 'tomorrow at 5pm' and return a date 1 week in the future. This has now been improved upon and seems to be more stable.
