### ISSUE TITLE
Checks for compatibility of bymonthday and bymonth have hardwired years

### ISSUE THREAD

**Issue by nickovs** [DavidAmison/natural_time#21]
The code that checks is the `bymonthday` value and `bymonth` value are compatible assumes some specific years (which are now several years in the past):
https://github.com/DavidAmison/natural_time/blob/e1e58d2adb176c16aba2ef2111f8c735874eb655/natural_time/natural_time_parser.py#L210-L213

**Comment by DavidAmison** [comment]
Clearly the initial implementation used hard-coded years. This should be relatively straightforward to resolve.

**Comment by DavidAmison** [comment]
Hard-coded years changed to be based on now.year
